version: '3.8'

services:
  web_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    ports:
      - 8000:8001
    env_file: .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db_service
      - redis_service
  #      - rabbitmq
  db_service:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  redis_service:
    image: redis:alpine

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web_service
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media


volumes:
  media_volume:
  static_volume:
  postgres_data:

























